language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
  - shellcheck -e SC2153 duplicity-backup.sh
  - shellcheck -e SC2034 duplicity-backup.conf.example

matrix:
  fast_finish: true
